### ISSUE TITLE
в футере вкладки меню должны быть кликабельны

### ISSUE THREAD

**Issue by VladyslavKovalchuk** [nicolaypetrovich/rocket-luxurymod#10]
и должно быть другое расположение блоков меню: http://prntscr.com/l3yq51
сейчас так: http://prntscr.com/l3yqbz

**Comment by VladyslavKovalchuk** [comment]
расположение блоков не менять, уточнил у Саши

**Comment by dchaika1990** [comment]
На заметку, футер на всех страница одинаковый. Очень редко, если он где-то меняется, зачастую это хотяк.
