### ISSUE TITLE
после нажатия на изображение в слайдере, оно растягивается только в ширину на всю ширину экрана, 

### ISSUE THREAD

**Issue by VladyslavKovalchuk** [nicolaypetrovich/rocket-luxurymod#6]
http://prntscr.com/kyz66f
http://prntscr.com/kyz43d
ие11

**Comment by dchaika1990** [comment]
На ие не работает функция для растягивания картинки, и так как картинка идет тегом img , то этот функционал не возможен. Считаю, что для ие это нах надо.

**Comment by dchaika1990** [comment]
Так как сайт будут натягивать на wp, то картинки в слайдер нужно вставлять картинкой, а не фоном. Решение - вставлять адекватные картинки, нарезанные wp

**Comment by VladyslavKovalchuk** [comment]
сейчас исправлено
