### ISSUE TITLE
андроид - ломается меню, стр модинг, модинг2

### ISSUE THREAD

**Issue by VladyslavKovalchuk** [nicolaypetrovich/rocket-luxurymod#8]
открываем меню, подменю, закрываем, слайдер с картинками сползает вниз, открываем меню еще раз, закрываем, слайдер исчезает
http://prntscr.com/kztd8i
 http://prntscr.com/kztdew
в опере, хроме, фф

**Comment by VladyslavKovalchuk** [comment]
на айфоне - открыть меню, подменю, закрыть меню - слайдер сползает
открыть меню, подменю, закрыть подменю, закрыть меню - слайдер исчезает

**Comment by dchaika1990** [comment]
сбрось кеш, или спроси у Саши, уже она сама проверила, все работает. На перой и второй странице одинаковый функционал и если работает на одной то и работает на второй, проверь
